stages:
  - trigger_downstream_merge_requests

variables:
  DOWNSTREAM_REPOS: "gomogi/indrz/aau/indrz-frontend-aau,gomogi/indrz/wu/indrz-frontend-wu,gomogi/indrz/tu/indrz-frontend-tu"  # Comma-separated list of downstream repositories

trigger_downstream_merge_requests:
  stage: trigger_downstream_merge_requests
  only:
    refs:
      - main
  script:
    - apt-get update -qy
    - apt-get install -y curl
    - >
      for downstream_repo in $(echo $DOWNSTREAM_REPOS | tr "," "\n"); do
        echo "Attempting to create merge request in downstream repository: $downstream_repo";

        # Create new merge request
        response=$(curl -s --request POST "https://gitlab.com/api/v4/projects/$downstream_repo/merge_requests" \
          --header "PRIVATE-TOKEN: $PRIVATE_ACCESS_TOKEN" \
          --form "source_branch=source_branch_in_downstream" \
          --form "target_branch=main" \
          --form "title=Automated Merge Request" \
          --form "description=This is an automated merge request triggered by an update to the main repository.")

        if [ "$(echo "$response" | grep -o 'id')" ]; then
          echo "Merge request created successfully in $downstream_repo."
        else
          echo "Failed to create merge request in $downstream_repo. Response: $response"
        fi
      done
