stages:
  - trigger_downstream_merge_requests

variables:
  DOWNSTREAM_REPO_IDS: "14108617,23077745,23077517"  # aau, tu, wu

trigger_downstream_merge_requests:
  stage: trigger_downstream_merge_requests
  only:
    refs:
      - main
  script:
    - apt-get update -qy
    - apt-get install -y curl
    - >
      for downstream_repo_id in $(echo $DOWNSTREAM_REPO_IDS | tr "," "\n"); do
        echo "Attempting to create merge request in downstream repository: $downstream_repo_id";

        # Create new merge request
        response=$(curl -s --request POST "https://gitlab.com/api/v4/projects/$downstream_repo_id/merge_requests" \
          --header "PRIVATE-TOKEN: $PRIVATE_ACCESS_TOKEN" \
          --form "source_branch=main" \
          --form "target_branch=main" \
          --form "title=Automated Merge Request" \
          --form "description=This is an automated merge request triggered by an update to the main repository.")
      
      
        http_status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTP_STATUS://')
  
        if [ "$http_status" != "200" ]; then
          echo "Merge request created successfully in $downstream_repo_id ."
        else
          echo "Failed to create merge request in $downstream_repo_id. Response: $response and fail code $http_status"
        fi
      done
