version: "3"

services:
  indrz-client:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: indrz-client
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  indrz-nginx-client:
    image: nginx:1.19
    container_name: indrz-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - indrz-client
