version: "3"

services:
  indrz_fe_nuxt:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: indrz-fe
    restart: always
    ports:
      - "3000:3000"
    command:
      "npm run start"

  nginx_fe:
    image: nginx:1.19
    container_name: indrz-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - indrz_fe_nuxt
